// <auto-generated />
using Loja.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Loja.Data.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20201213042314_usuario")]
    partial class usuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Loja.Domain.Model.Usuarios.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Loja.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Action")
                        .HasColumnType("bit");

                    b.Property<string>("description")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("img")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Loja.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("brandid")
                        .HasColumnType("int");

                    b.Property<int>("categoryid")
                        .HasColumnType("int");

                    b.Property<int>("detailsid")
                        .HasColumnType("int");

                    b.Property<string>("img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("sale")
                        .HasColumnType("bit");

                    b.Property<decimal>("salePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("shortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("subCategoriaid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("brandid");

                    b.HasIndex("categoryid");

                    b.HasIndex("detailsid");

                    b.HasIndex("subCategoriaid");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Loja.Domain.Models.gallery", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subtitle")
                        .HasColumnType("varchar(30)");

                    b.HasKey("id");

                    b.ToTable("galleries");
                });

            modelBuilder.Entity("Loja.Domain.Models.product.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Action")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("brand");
                });

            modelBuilder.Entity("Loja.Domain.Models.product.Details", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Garantia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProdutoPeso")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("dimensoesEmbalagemA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("dimensoesEmbalagemL")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("dimensoesEmbalagemP")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("dimensoesProdutoA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("dimensoesProdutoL")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("dimensoesProdutoP")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("embalagemPeso")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("detail");
                });

            modelBuilder.Entity("Loja.Domain.Models.product.Specs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("color")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("galleryid")
                        .HasColumnType("int");

                    b.Property<int>("productid")
                        .HasColumnType("int");

                    b.Property<decimal>("size")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("specs")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("typeid")
                        .HasColumnType("int");

                    b.Property<string>("warranty")
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("galleryid");

                    b.HasIndex("productid");

                    b.HasIndex("typeid");

                    b.ToTable("specs");
                });

            modelBuilder.Entity("Loja.Domain.Models.product.SubCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Action")
                        .HasColumnType("bit");

                    b.Property<int>("categoryid")
                        .HasColumnType("int");

                    b.Property<string>("img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("categoryid");

                    b.ToTable("SubCategoria");
                });

            modelBuilder.Entity("Loja.Domain.Models.product.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Action")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("type");
                });

            modelBuilder.Entity("Loja.Domain.Models.Product", b =>
                {
                    b.HasOne("Loja.Domain.Models.product.Brand", "brand")
                        .WithMany()
                        .HasForeignKey("brandid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loja.Domain.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("categoryid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loja.Domain.Models.product.Details", "details")
                        .WithMany()
                        .HasForeignKey("detailsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loja.Domain.Models.product.SubCategoria", "subCategoria")
                        .WithMany()
                        .HasForeignKey("subCategoriaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Loja.Domain.Models.product.Specs", b =>
                {
                    b.HasOne("Loja.Domain.Models.gallery", "gallery")
                        .WithMany()
                        .HasForeignKey("galleryid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loja.Domain.Models.Product", "product")
                        .WithMany()
                        .HasForeignKey("productid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loja.Domain.Models.product.Type", "type")
                        .WithMany()
                        .HasForeignKey("typeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Loja.Domain.Models.product.SubCategoria", b =>
                {
                    b.HasOne("Loja.Domain.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("categoryid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
